# Generated by Django 5.2.7 on 2025-11-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_root', '0002_alter_post_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
