# Generated by Django 5.2.7 on 2025-11-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_root', '0003_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(unique=True),
        ),
    ]
