# Generated by Django 5.2.7 on 2025-11-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_root', '0004_alter_post_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='datetime',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_info',
            field=models.TextField(),
        ),
    ]
