# Generated by Django 5.2.7 on 2025-11-29 22:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_root', '0006_rename_profile_pic_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
