# Generated by Django 5.2.7 on 2025-12-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_root', '0008_alter_likes_like_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
