# Generated by Django 5.2.7 on 2025-12-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_root', '0010_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='media/profile_images/default.webp', upload_to='media/profile_images/'),
        ),
    ]
